# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  mowgul.com:
    site_hosts:
      - canonical: mowgul.dev
        redirects:
          - www.mowgul.com
    local_path: ../ghettifish.com # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: nic@ghettifish.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
  ghettifish.com:
    site_hosts:
      - canonical: ghettifish.dev
        redirects:
          - www.ghettifish.com
    local_path: ../ghettifish.com # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: nic@ghettifish.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
  nicbovee.com:
    site_hosts:
      - canonical: nicbovee.dev
        redirects:
          - www.nicbovee.com
    local_path: ../nicbovee.com # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: nic@ghettifish.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
  writeastoryfor.me:
    site_hosts:
      - canonical: writeastoryfor.dev
        redirects:
          - writeastoryfor.me
    local_path: ../writeastoryfor.me # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: nic@ghettifish.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
